# default configure
app:
  port: 3000
  log_level: debug
  crontime: "*/5 * * * *"

uptimerobot:
  api_key:
  pattern: "%group/%name"
  statuses: "2-9"

website:
  title: "Uptime Robot Status"
  copyright: "Uptime Robot"
  links:
    - name: Blog
      href: https://learningman.top
