app:
  port: 3000
  log_level: info
  crontime: "*/5 * * * *"

uptimerobot:
  api_key: fake_api_key
  pattern: "%group/%name"
  statuses: "2-9"

website:
  title: "Zxilly Cloud Status"
  copyright: "Zxilly"
  links:
    - name: Blog
      href: https://learningman.top
